# -*- coding: utf-8 -*-
"""Dataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tk2rEWlCXSW3zDoHyTspaRlJlEqNH37q
"""



"""**Enlace a archivo guardado en Drive**"""

from google.colab import drive

drive.mount('/content/drive')

"""**Carga del Dataset**"""

import pandas as pd

import numpy as np

datos = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataframes/winemag-data_first150k.csv',index_col=0)



datos.head(5)

"""**Informacion del Dataset**

"""

datos.shape

datos.info()

datos.describe()

datos.price.describe()

datos.index

datos.columns

columnas = datos.columns
columnas

type(columnas)

"""Formas de visualizar y seleccionar porcionaes del dataframe"""

datos.tail(3)

datos.country

datos['province']

datos.province

datos['country'][3]

"""Obtener los datos por indice - iloc"""

datos.iloc[:,1]

datos.iloc[:3,2:6]

datos.iloc[[2,4,10],0]

datos.iloc[-6:]

"""**Seleccion de celdas por nombres de columnas - loc**"""

datos.loc[4,'country']

datos.loc[1:5,['country', 'points']]

#datos = datos.set_index(['country'])
#datos.head(3)

datos.head(5)

"""Filtrar y Seleccionar"""

datos.country=='US'

datos.loc[datos.country=='US']

datos_filtrados = datos.loc[(datos.points>90)&(datos.country=='US')]

datos_filtrados.head(5)

datos_filtrados_o = datos.loc[(datos.points>120)|(datos.country=='US')]

datos_filtrados_o.head(10)

datos.loc[datos.country.isin(['US','France'])]

datos.loc[datos.price.notnull()]

datos.loc[datos.price.isnull()]

"""Asignar valores a nueva columna"""

datos['NuevaColumna'] = datos['price']*3

datos[['price','NuevaColumna']]

datos.price.mean()

"""Operaciones con Nulos"""

columnas_nulos = datos.columns[datos.isnull().any()]
datos[columnas_nulos].isnull().sum()

datos.isnull().sum()

datos.isnull().any()

datos_sin_nulos = datos.dropna(how='any')

datos_sin_nulos.isnull().sum()

datos.shape

datos_sin_nulos.shape

"""Valores Unicos"""

datos.country.unique()

datos.country.value_counts()

media_puntos = datos.points.mean()
mediana_puntos = datos.points.median()

print(media_puntos)
print(mediana_puntos)

datos.points.map(lambda punto: punto - media_puntos)

"""**Agrupaciones**"""

datos_agrupados_pais = datos.groupby('country').points.count()
datos_agrupados_pais.head(20)

datos_agrupados_pais = datos.groupby('country').price.min()
datos_agrupados_pais.head(20)

datos_agrupados_pais = datos.groupby(['country','points']).price.agg([min,max])
datos_agrupados_pais.head(20)

datos.sort_values(by='points',ascending=False)

datos.price.dtype

datos.country.dtype

datos.dtypes

datos.points = datos.points.astype('float64')

datos.points.dtype

"""Reemplazar Datos"""

datos.head(5)

datos.country = datos.country.replace('US','EEUU')
datos.head(10)

datos.rename(columns={'points':'puntos', 'price':'precio'})

datos.rename(index={1:'SegundaFile', 2:'terceraFila'})

datos.rename_axis('vinos',axis='rows').rename_axis('campos',axis='columns')

"""Combinar Dataframes"""

datosUSA=datos[datos.country=='EEUU']
datosFrancia=datos[datos.country=='France']

datosUSA.head(5)

datosFrancia.head(5)

datosUnidos = pd.concat([datosUSA,datosFrancia])

datosUnidos.head(5)

datosUnidos.tail(5)